# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: markets/index.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cws.markets import market_pb2 as markets_dot_market__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='markets/index.proto',
  package='ProtobufMarkets',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13markets/index.proto\x12\x0fProtobufMarkets\x1a\x14markets/market.proto\"q\n\x05Index\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x11\n\tindexType\x18\x03 \x01(\t\x12\x0f\n\x07\x63wIndex\x18\x04 \x01(\x08\x12\x12\n\nexchangeId\x18\x05 \x01(\x04\x12\x14\n\x0cinstrumentId\x18\x06 \x01(\x04\"\xaf\x02\n\x12IndexUpdateMessage\x12%\n\x05index\x18\x01 \x01(\x0b\x32\x16.ProtobufMarkets.Index\x12\x35\n\x0ctickerUpdate\x18\x02 \x01(\x0b\x32\x1d.ProtobufMarkets.TickerUpdateH\x00\x12;\n\x0fintervalsUpdate\x18\x03 \x01(\x0b\x32 .ProtobufMarkets.IntervalsUpdateH\x00\x12\x37\n\rsummaryUpdate\x18\x04 \x01(\x0b\x32\x1e.ProtobufMarkets.SummaryUpdateH\x00\x12;\n\x0fsparklineUpdate\x18\x05 \x01(\x0b\x32 .ProtobufMarkets.SparklineUpdateH\x00\x42\x08\n\x06Update\"8\n\x0cTickerUpdate\x12(\n\x07tickers\x18\x01 \x03(\x0b\x32\x17.ProtobufMarkets.Ticker\"A\n\x06Ticker\x12\r\n\x05value\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x15\n\rtimestampNano\x18\x03 \x01(\x03\x62\x06proto3')
  ,
  dependencies=[markets_dot_market__pb2.DESCRIPTOR,])




_INDEX = _descriptor.Descriptor(
  name='Index',
  full_name='ProtobufMarkets.Index',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ProtobufMarkets.Index.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='ProtobufMarkets.Index.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indexType', full_name='ProtobufMarkets.Index.indexType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cwIndex', full_name='ProtobufMarkets.Index.cwIndex', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchangeId', full_name='ProtobufMarkets.Index.exchangeId', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrumentId', full_name='ProtobufMarkets.Index.instrumentId', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=175,
)


_INDEXUPDATEMESSAGE = _descriptor.Descriptor(
  name='IndexUpdateMessage',
  full_name='ProtobufMarkets.IndexUpdateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='ProtobufMarkets.IndexUpdateMessage.index', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tickerUpdate', full_name='ProtobufMarkets.IndexUpdateMessage.tickerUpdate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intervalsUpdate', full_name='ProtobufMarkets.IndexUpdateMessage.intervalsUpdate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summaryUpdate', full_name='ProtobufMarkets.IndexUpdateMessage.summaryUpdate', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sparklineUpdate', full_name='ProtobufMarkets.IndexUpdateMessage.sparklineUpdate', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Update', full_name='ProtobufMarkets.IndexUpdateMessage.Update',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=178,
  serialized_end=481,
)


_TICKERUPDATE = _descriptor.Descriptor(
  name='TickerUpdate',
  full_name='ProtobufMarkets.TickerUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tickers', full_name='ProtobufMarkets.TickerUpdate.tickers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=539,
)


_TICKER = _descriptor.Descriptor(
  name='Ticker',
  full_name='ProtobufMarkets.Ticker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ProtobufMarkets.Ticker.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ProtobufMarkets.Ticker.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestampNano', full_name='ProtobufMarkets.Ticker.timestampNano', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=606,
)

_INDEXUPDATEMESSAGE.fields_by_name['index'].message_type = _INDEX
_INDEXUPDATEMESSAGE.fields_by_name['tickerUpdate'].message_type = _TICKERUPDATE
_INDEXUPDATEMESSAGE.fields_by_name['intervalsUpdate'].message_type = markets_dot_market__pb2._INTERVALSUPDATE
_INDEXUPDATEMESSAGE.fields_by_name['summaryUpdate'].message_type = markets_dot_market__pb2._SUMMARYUPDATE
_INDEXUPDATEMESSAGE.fields_by_name['sparklineUpdate'].message_type = markets_dot_market__pb2._SPARKLINEUPDATE
_INDEXUPDATEMESSAGE.oneofs_by_name['Update'].fields.append(
  _INDEXUPDATEMESSAGE.fields_by_name['tickerUpdate'])
_INDEXUPDATEMESSAGE.fields_by_name['tickerUpdate'].containing_oneof = _INDEXUPDATEMESSAGE.oneofs_by_name['Update']
_INDEXUPDATEMESSAGE.oneofs_by_name['Update'].fields.append(
  _INDEXUPDATEMESSAGE.fields_by_name['intervalsUpdate'])
_INDEXUPDATEMESSAGE.fields_by_name['intervalsUpdate'].containing_oneof = _INDEXUPDATEMESSAGE.oneofs_by_name['Update']
_INDEXUPDATEMESSAGE.oneofs_by_name['Update'].fields.append(
  _INDEXUPDATEMESSAGE.fields_by_name['summaryUpdate'])
_INDEXUPDATEMESSAGE.fields_by_name['summaryUpdate'].containing_oneof = _INDEXUPDATEMESSAGE.oneofs_by_name['Update']
_INDEXUPDATEMESSAGE.oneofs_by_name['Update'].fields.append(
  _INDEXUPDATEMESSAGE.fields_by_name['sparklineUpdate'])
_INDEXUPDATEMESSAGE.fields_by_name['sparklineUpdate'].containing_oneof = _INDEXUPDATEMESSAGE.oneofs_by_name['Update']
_TICKERUPDATE.fields_by_name['tickers'].message_type = _TICKER
DESCRIPTOR.message_types_by_name['Index'] = _INDEX
DESCRIPTOR.message_types_by_name['IndexUpdateMessage'] = _INDEXUPDATEMESSAGE
DESCRIPTOR.message_types_by_name['TickerUpdate'] = _TICKERUPDATE
DESCRIPTOR.message_types_by_name['Ticker'] = _TICKER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Index = _reflection.GeneratedProtocolMessageType('Index', (_message.Message,), dict(
  DESCRIPTOR = _INDEX,
  __module__ = 'markets.index_pb2'
  # @@protoc_insertion_point(class_scope:ProtobufMarkets.Index)
  ))
_sym_db.RegisterMessage(Index)

IndexUpdateMessage = _reflection.GeneratedProtocolMessageType('IndexUpdateMessage', (_message.Message,), dict(
  DESCRIPTOR = _INDEXUPDATEMESSAGE,
  __module__ = 'markets.index_pb2'
  # @@protoc_insertion_point(class_scope:ProtobufMarkets.IndexUpdateMessage)
  ))
_sym_db.RegisterMessage(IndexUpdateMessage)

TickerUpdate = _reflection.GeneratedProtocolMessageType('TickerUpdate', (_message.Message,), dict(
  DESCRIPTOR = _TICKERUPDATE,
  __module__ = 'markets.index_pb2'
  # @@protoc_insertion_point(class_scope:ProtobufMarkets.TickerUpdate)
  ))
_sym_db.RegisterMessage(TickerUpdate)

Ticker = _reflection.GeneratedProtocolMessageType('Ticker', (_message.Message,), dict(
  DESCRIPTOR = _TICKER,
  __module__ = 'markets.index_pb2'
  # @@protoc_insertion_point(class_scope:ProtobufMarkets.Ticker)
  ))
_sym_db.RegisterMessage(Ticker)


# @@protoc_insertion_point(module_scope)
